#!/bin/bash

NAME="citystats"
DJANGODIR="/home/ubuntu/citystats/seattlestats/"
SOCKFILE="/home/ubuntu/citystats/run/gunicorn.sock"
NUM_WORKERS=3
DJANGO_SETTINGS_MODULE=seattlestats.settings.prod
DJANGO_WSGI_MODULE=seattlestats.wsgi

echo "Starting $NAME as `whoami`"

cd $DJANGODIR
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start virtualenv
source /home/ubuntu/citystats/venv/bin/activate

# Start your Django unicorn
# Programs meant to be run under supervisor should not daemonize themselves
exec gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --bind=unix:$SOCKFILE \
  --log-level=debug \
  --log-file=-
